apiVersion: v1
kind: Service
metadata:
  name: {{ include "agro-app.fullname" . }}
  labels:
    {{- include "agro-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agro-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 8000

